version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: python311-img
    container_name: python311-cont
    volumes:
      - .:/workspace
      - vscode_extensions:/root/.vscode-server/extensions
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  vscode_extensions:
